# Generated by Django 4.2.5 on 2023-10-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_assistant_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medicament',
        ),
        migrations.AddField(
            model_name='patient',
            name='medicament',
            field=models.ManyToManyField(default=None, related_name='patients', to='hospital.medicament'),
        ),
    ]
